# Generated by Django 3.2.3 on 2021-06-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agenda', '0005_auto_20210602_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
