# Generated by Django 3.2.3 on 2021-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agenda', '0007_alter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
