# Generated by Django 3.2.3 on 2021-06-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_agenda', '0009_auto_20210605_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
